default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

stages:
  - build
  - deploy

variables:
  POSTGRES_DB: empmanagement
  POSTGRES_USER: ${DB_USERNAME}
  POSTGRES_PASSWORD: ${DB_PASSWORD}
  POSTGRES_HOST: ${END_POINT}

build-frontend:
  stage: build
  script:
    - echo "Building the frontend..."
    - cd Frontend/EmpManagementApp
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t duydang812/emp_management_fe:$CI_COMMIT_SHA .
    - docker push duydang812/emp_management_fe:$CI_COMMIT_SHA
  # artifacts:
  #   paths:
  #     - Frontend/EmpManagementApp/build

build-backend:
  stage: build
  script:
    - echo "Building the backend..."
    - cd Backend/EmpManagementAPI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t duydang812/emp_management:$CI_COMMIT_SHA .
    - docker push duydang812/emp_management:$CI_COMMIT_SHA
  # artifacts:
  #   paths:
  #     - Backend/EmpManagementAPI/build/libs/*.jar

deploy-frontend:
  stage: deploy
  script:
    - echo "Deploying the frontend..."
    - docker pull duydang812/emp_management_fe:$CI_COMMIT_SHA
    - docker rm -f emp-management-fe-container
    - docker run -d -p 3000:3000 --name emp-management-fe-container -e REACT_APP_API_URL=$REACT_APP_API_URL duydang812/emp_management_fe:$CI_COMMIT_SHA
  tags:
    - ec2-runner-2

deploy_backend:
  stage: deploy
  script:
    - echo "Deploying the backend..."
    - docker pull duydang812/emp_management:$CI_COMMIT_SHA
    - docker rm -f emp-management-container
    - docker run -d -p 8080:8080 --name emp-management-container -e END_POINT=$END_POINT -e DB_USERNAME=$DB_USERNAME -e DB_PASSWORD=$DB_PASSWORD -e DB=$DB_NAME duydang812/emp_management:$CI_COMMIT_SHA
  tags:
    - ec2-runner
